version: 0.2
run-as: root

phases:
  pre_build:
    commands:
      - echo "Configuring AWS CLI..."
      - aws configure set region $AWS_REGION
      - aws sts get-caller-identity
      - echo "Fetching Docker Hub credentials from AWS Secrets Manager..."
      - export DOCKER_USERNAME=$(aws ssm get-parameter --name /devsecops/DockerUser --with-decryption --query "Parameter.Value" --output text)
      - export DOCKER_PASSWORD=$(aws ssm get-parameter --name /devsecops/DockerPasswd --with-decryption --query "Parameter.Value" --output text)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - |
        PAYLOAD=$(echo -n "{\"branch\": \"$GitHubBranch\"}" | base64)
      - aws lambda invoke --function-name ${ProjectName}-GenerateScanNameCD --payload "$PAYLOAD" response.json
      - SCAN_NAME=$(cat response.json | jq -r '.scan_name')
      - echo "timestamp=$SCAN_NAME"
  build:
    commands:
      - echo "Running CS-Suite inside Docker..."
      - mkdir -p $(pwd)/reports
      - |
        docker run --rm \
          -e AWS_ACCESS_KEY_ID="$(aws ssm get-parameter --name /devsecops/AccessKey_for_cs_suite --with-decryption --query 'Parameter.Value' --output text)" \
          -e AWS_SECRET_ACCESS_KEY="$(aws ssm get-parameter --name /devsecops/SecretKey_for_cs_suite --with-decryption --query 'Parameter.Value' --output text)" \
          -v $(pwd)/reports:/app/reports \
          securityftw/cs-suite:dependabot_pip_urllib3-1.26.5 -env aws || true
  post_build:
    commands:
      - echo "Uploading CS-Suite reports to S3..."
      - aws s3 cp $(pwd)/reports s3://$ARTIFACT_BUCKET/secureline-output/${GitHubRepo}/$SCAN_NAME/CloudSecurityScanResults/ --recursive

artifacts:
  files:
    - "**/final_json"
  discard-paths: no
  base-directory: reports
