version: 0.2
run-as: root

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip3 install --upgrade pip
      - pip3 install pipx
      - python3 -m pipx ensurepath
      - export PATH=$PATH:/root/.local/bin  # Ensure Prowler is in PATH
      - pipx install prowler
      - echo "Prowler installation completed."
      - prowler --version  # Verify installation

  pre_build:
    commands:
      - echo "Configuring AWS CLI..."
      - aws configure set region $AWS_REGION
      - aws sts get-caller-identity
      - echo "Fetching Docker Hub credentials from AWS Secrets Manager..."
      - export DOCKER_USERNAME=$(aws ssm get-parameter --name /devsecops/DockerUser --with-decryption --query "Parameter.Value" --output text)
      - export DOCKER_PASSWORD=$(aws ssm get-parameter --name /devsecops/DockerPasswd --with-decryption --query "Parameter.Value" --output text)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - |
        PAYLOAD=$(echo -n "{\"executionId\": \"$CODEPIPELINE_EXECUTION_ID\"}" | base64)
      - aws lambda invoke --function-name ${ProjectName}-GenerateScanNameCD --payload "$PAYLOAD" response.json
      - SCAN_NAME=$(cat response.json | jq -r '.scan_name')
      - echo "timestamp=$SCAN_NAME"
        #- export AWS_DEFAULT_REGION=us-east-1i
        #- export AWS_ACCESS_KEY_ID=$(aws ssm get-parameter --name /devsecops/AccessKey_for_cs_suite --with-decryption --query "Parameter.Value" --output text)
        #- export AWS_SECRET_ACCESS_KEY=$(aws ssm get-parameter --name /devsecops/SecretKey_for_cs_suite --with-decryption --query "Parameter.Value" --output text)
  build:
    commands:
      - echo "Running Prowler AWS Security Scan..."
      - mkdir -p $(pwd)/output
      - export PATH=$PATH:/root/.local/bin  # Ensure PATH is set
      - |
        docker run --rm \
          -v $(pwd)/output:/home/prowler/output \
          --name prowler \
          -e AWS_ACCESS_KEY_ID="$(aws ssm get-parameter --name /devsecops/AccessKey_for_cs_suite --with-decryption --query 'Parameter.Value' --output text)" \
          -e AWS_SECRET_ACCESS_KEY="$(aws ssm get-parameter --name /devsecops/SecretKey_for_cs_suite --with-decryption --query 'Parameter.Value' --output text)" \
          --user 0 \
          toniblyx/prowler:latest aws --ignore-exit-code-3 --output-filename prowler-cloud-scan-result || echo "Prowler scan completed with security findings, but not treated as a failure."
      - ls -lhtr $(pwd)/output
        #- prowler aws --output-filename prowler-cloud-scan-result --output-directory prowler_output

  post_build:
    commands:
      - echo "Uploading Prowler scan results to S3..."
      - aws s3 cp $(pwd)/output/ s3://$ARTIFACT_BUCKET/secureline-output/${GitHubRepo}/$SCAN_NAME/ProwlerResults/ --recursive
      - echo "Prowler scan completed."

artifacts:
  files:
    - "prowler-cloud-scan-*"
  discard-paths: no
  base-directory: output

