version: 0.2

phases:
  install:
    commands:
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

  pre_build:
    commands:
      # Check if Dockerfile exists
      - |
        if ! find . -name "Dockerfile" -type f | grep -q .; then
          echo "No Dockerfile found - creating empty results"
          echo '{"Results":[]}' > trivy-results.json
          echo '{"Results":[]}' > trivy-config-results.json
          exit 0
        fi
      - echo "Dockerfile found - proceeding with Trivy scan"
      - echo $CODEPIPELINE_EXECUTION_ID
      - |
        PAYLOAD=$(echo -n "{\"executionId\": \"$CODEPIPELINE_EXECUTION_ID\"}" | base64)
      - aws lambda invoke --function-name ${ProjectName}-GenerateScanNameCI --payload "$PAYLOAD" response.json      
      - SCAN_NAME=$(cat response.json | jq -r '.scan_name')
      - echo "timestamp=$SCAN_NAME"

  build:
    commands:
      - echo "Running Trivy scan..."
      - trivy fs . --format json -o trivy-results.json || true
      - trivy config . --format json -o trivy-config-results.json || true
      - ls -la
      
  post_build:
    commands:
      - |
        TIMESTAMP=$(date +%Y-%m-%d-%H-%M)
        if [ -f "trivy-results.json" ]; then
          aws s3 cp trivy-results.json s3://${RESULTS_BUCKET}/secureline-output/${GitHubRepo}/$SCAN_NAME/ContainerMisconfigScanResults/fs-scan.json
        else
          echo "FS scan results not found, creating empty one"
          echo '{"Results":[]}' > trivy-results.json
          aws s3 cp trivy-results.json s3://${RESULTS_BUCKET}/secureline-output/${GitHubRepo}/$SCAN_NAME/ContainerMisconfigScanResults/fs-scan.json
        fi
        
        if [ -f "trivy-config-results.json" ]; then
          aws s3 cp trivy-config-results.json s3://${RESULTS_BUCKET}/secureline-output/${GitHubRepo}/$SCAN_NAME/ContainerMisconfigScanResults/Trivy_Misconfig_result.json
        else
          echo "Config scan results not found, creating empty one"
          echo '{"Results":[]}' > trivy-config-results.json
          aws s3 cp trivy-config-results.json s3://${RESULTS_BUCKET}/secureline-output/${GitHubRepo}/$SCAN_NAME/ContainerMisconfigScanResults/Trivy_Misconfig_result.json
        fi

artifacts:
  files:
    - trivy-results.json
    - trivy-config-results.json
  base-directory: .
