version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies for Secret Scanning..."
      - pip install --upgrade trufflehog3
      - echo $CODEPIPELINE_EXECUTION_ID
      - |
        PAYLOAD=$(echo -n "{\"executionId\": \"$CODEPIPELINE_EXECUTION_ID\"}" | base64)
      - aws lambda invoke --function-name ${ProjectName}-GenerateScanNameCI --payload "$PAYLOAD" response.json      
      - SCAN_NAME=$(cat response.json | jq -r '.scan_name')
      - echo "timestamp=$SCAN_NAME"
  build:
    commands:
      - echo "Starting TruffleHog scan for secret keys..."
      - |
        trufflehog3 -f json -o trufflehog_output.json || true 

  post_build:
    commands:
      - echo "Checking scan results..."
      - TIMESTAMP=$(date +%Y-%m-%d-%H-%M)

      - if [ -f "trufflehog_output.json" ]; then
          echo "Uploading scan results to S3...";
          aws s3 cp trufflehog_output.json s3://${RESULTS_BUCKET}/secureline-output/${GitHubRepo}/$SCAN_NAME/SecretScanResults/trufflehog_output.json;
        else
          echo "Scan results not found, creating an empty one...";
          echo '{"Results":[]}' > trufflehog_output.json;
          aws s3 cp trufflehog_output.json s3://${RESULTS_BUCKET}/secureline-output/${GitHubRepo}/$SCAN_NAME/SecretScanResults/trufflehog_output.json;
        fi

artifacts:
  files:
    - trufflehog_output.json
  base-directory: .

